export const MODELS = [
  {
    slug: "spiderman",
    name: "Hombre Araña",
    cardTitle: "🕷️ Hombre Araña",
    altText: "Figura de papel del Hombre Araña armado con técnica papercraft, con dos variantes de textura para elegir",
    image: "uploads/Spiderman-preview.png",
    model3d: "uploads/Spiderman.glb",
    pdfUrl: "uploads/Spiderman-e8254ea9.pdf",
    category: "series",
    categoryLabel: "Series y Películas",
    difficulty: "facil",
    difficultyLabel: "⭐ Fácil",
    time: "40 min",
    badge: "✨ Recién salido del horno",
    tagNew: true,
    description: "El trepamuros en versión papercraft. Elige tu textura favorita antes de descargar: clásico cómic o pop-art retro.",
    materials: ["Tijeras", "Papel (120g o más)", "Impresora"],
    textures: [
      { label: "Clásico", image: "uploads/Spiderman-text1.png", pdfUrl: "uploads/Spiderman-e8254ea9.pdf", model3d: "uploads/Spiderman.glb" },
      { label: "Pop-Art", image: "uploads/Spiderman-text2.png", pdfUrl: "uploads/Spiderman2-d09194b0.pdf", model3d: "uploads/Spiderman variante.glb" }
    ]
  },
  {
    slug: "conejito",
    name: "Conejito",
    cardTitle: "🐰 Conejito",
    altText: "Figura de papel de un conejito con orejas largas armado en papercraft",
    image: "uploads/Conejito.png",
    model3d: "uploads/Conejito.glb",
    pdfUrl: "uploads/Conejito.pdf",
    category: "animales",
    categoryLabel: "Animales",
    difficulty: "facil",
    difficultyLabel: "⭐ Fácil",
    time: "20 min",
    badge: "🌱 Ideal para empezar",
    tagNew: true,
    description: "Tierno, orejón y con cachetes rosados. Un modelo simple y adorable para sumar a tu colección de animales.",
    materials: ["Tijeras", "Papel (120g o más)", "Impresora"]
  },
  {
    slug: "capibara",
    name: "Capibara relajado",
    cardTitle: "🐹 Capibara relajado",
    altText: "Figura de papel de un capibara armado con técnica papercraft, modelo fácil de imprimir y recortar",
    image: "uploads/Capibara-4a38801a.png",
    model3d: "uploads/Capibara-4da6887f.glb",
    pdfUrl: "uploads/Capibara-01caf8f4.pdf",
    category: "animales",
    categoryLabel: "Animales",
    difficulty: "facil",
    difficultyLabel: "⭐ Fácil",
    time: "20 min",
    badge: "🌱 Ideal para empezar",
    tagNew: true,
    description: "El más zen de todos. Este capibara de papel no se altera por nada — perfecto compañero de escritorio y tu primer modelo si nunca armaste papercraft.",
    materials: ["Tijeras", "Papel (120g o más)", "Impresora"]
  },
  {
    slug: "gatito",
    name: "Gatito dormido",
    cardTitle: "😴 Gatito dormido",
    altText: "Figura de papel de un gatito dormido hecho en papercraft, ideal para principiantes",
    image: "uploads/Gatito dormido-def393ea.png",
    model3d: "uploads/Gatito dormido.glb",
    pdfUrl: "uploads/Gatito Dormido.pdf",
    category: "animales",
    categoryLabel: "Animales",
    difficulty: "facil",
    difficultyLabel: "⭐ Fácil",
    time: "25 min",
    badge: "🌱 Ideal para empezar",
    tagNew: true,
    description: "Un gatito hecho bolita, soñando tranquilo. Sus formas simples lo hacen ideal para armar con niños o mientras ves una serie.",
    materials: ["Tijeras", "Papel (120g o más)", "Impresora"]
  },
  {
    slug: "cactus",
    name: "Cactus feliz",
    cardTitle: "🌵 Cactus feliz",
    altText: "Figura de papel de un cactus sonriente armado en papercraft para decorar tu escritorio",
    image: "uploads/Cactus-ac52ac16.png",
    model3d: "uploads/Cactus.glb",
    pdfUrl: "uploads/Cactus.pdf",
    category: "plantas",
    categoryLabel: "Plantas",
    difficulty: "medio",
    difficultyLabel: "🔥 Solo para valientes",
    time: "15 min",
    badge: "🔥 Solo para valientes",
    tagNew: true,
    description: "La planta que nunca vas a olvidar regar. Ideal para decorar tu escritorio con algo que siempre sonríe.",
    materials: ["Tijeras", "Papel (120g o más)", "Impresora"]
  },
  {
    slug: "perrito",
    name: "Perrito dormido",
    cardTitle: "🐶 Perrito dormido",
    altText: "Figura de papel de un perrito dormido con orejas largas hecho en papercraft",
    image: "uploads/Perrito dormido-c9a8efcd.png",
    model3d: "uploads/Perro durmiendo-b93e216d.glb",
    pdfUrl: "uploads/Perrito dormido.pdf",
    category: "animales",
    categoryLabel: "Animales",
    difficulty: "facil",
    difficultyLabel: "⭐ Fácil",
    time: "20 min",
    badge: "🌱 Ideal para empezar",
    tagNew: true,
    description: "Orejas larguísimas y una siesta eterna. Uno de los modelos más queridos de la comunidad PaperTok.",
    materials: ["Tijeras", "Papel (120g o más)", "Impresora"]
  },
  {
    slug: "eleven",
    name: "Eleven",
    cardTitle: "👧 Eleven",
    altText: "Figura de papel de Eleven de Stranger Things armada en papercraft",
    image: "uploads/Eleven.png",
    model3d: "uploads/Eleven.glb",
    pdfUrl: "uploads/Eleven.pdf",
    category: "series",
    categoryLabel: "Series y Películas",
    difficulty: "facil",
    difficultyLabel: "⭐ Fácil",
    time: "40 min",
    badge: "🌱 Ideal para empezar",
    tagNew: true,
    description: "Del Upside Down directo a tu escritorio. Un modelo con más piezas, ideal cuando ya le agarraste la mano al papercraft.",
    materials: ["Tijeras", "Papel (120g o más)", "Impresora", "Pegamento"]
  },
  {
    slug: "vhs",
    name: "Casette VHS retro",
    cardTitle: "📼 Casette VHS retro",
    altText: "Figura de papel de un casette VHS retro armado en papercraft",
    image: "uploads/Casette VHS-5032e151.png",
    model3d: "uploads/Casette VHS.glb",
    pdfUrl: "uploads/Casette VHS.pdf",
    category: "retro",
    categoryLabel: "Retro",
    difficulty: "facil",
    difficultyLabel: "⭐ Fácil",
    time: "45 min",
    badge: "🌱 Ideal para empezar",
    tagNew: true,
    description: "Un clásico noventero con más dobleces de lo que aparenta. Perfecto para quienes quieren un reto extra este fin de semana.",
    materials: ["Tijeras", "Papel (120g o más)", "Impresora", "Pegamento"]
  },
  {
    slug: "dustin",
    name: "Dustin",
    cardTitle: "🧢 Dustin",
    altText: "Figura de papel de Dustin de Stranger Things armada en papercraft",
    image: "uploads/Dustin.png",
    model3d: "uploads/Dustin.glb",
    pdfUrl: "uploads/Dustin.pdf",
    category: "series",
    categoryLabel: "Series y Películas",
    difficulty: "facil",
    difficultyLabel: "⭐ Fácil",
    time: "40 min",
    badge: "🌱 Ideal para empezar",
    tagNew: true,
    description: "El explorador del grupo, listo para su próxima aventura en Hawkins. Un modelo divertido para sumar a tu colección del grupo.",
    materials: ["Tijeras", "Papel (120g o más)", "Impresora", "Pegamento"]
  },
  {
    slug: "lucas",
    name: "Lucas",
    cardTitle: "🎯 Lucas",
    altText: "Figura de papel de Lucas de Stranger Things armada en papercraft",
    image: "uploads/Lucas.png",
    model3d: "uploads/Lucas.glb",
    pdfUrl: "uploads/Lucas.pdf",
    category: "series",
    categoryLabel: "Series y Películas",
    difficulty: "facil",
    difficultyLabel: "⭐ Fácil",
    time: "40 min",
    badge: "🌱 Ideal para empezar",
    tagNew: true,
    description: "Siempre alerta y con la honda lista. Completa tu colección de papel con este miembro clave del grupo.",
    materials: ["Tijeras", "Papel (120g o más)", "Impresora", "Pegamento"]
  },
  {
    slug: "max",
    name: "Max",
    cardTitle: "🛹 Max",
    altText: "Figura de papel de Max de Stranger Things armada en papercraft",
    image: "uploads/Max.png",
    model3d: "uploads/Max.glb",
    pdfUrl: "uploads/Max.pdf",
    category: "series",
    categoryLabel: "Series y Películas",
    difficulty: "facil",
    difficultyLabel: "⭐ Fácil",
    time: "40 min",
    badge: "🌱 Ideal para empezar",
    tagNew: true,
    description: "La incorporación más audaz del grupo. Un modelo lleno de personalidad para tu escritorio.",
    materials: ["Tijeras", "Papel (120g o más)", "Impresora", "Pegamento"]
  },
  {
    slug: "mike",
    name: "Mike",
    cardTitle: "📻 Mike",
    altText: "Figura de papel de Mike de Stranger Things armada en papercraft",
    image: "uploads/Mike.png",
    model3d: "uploads/Mike.glb",
    pdfUrl: "uploads/Mike.pdf",
    category: "series",
    categoryLabel: "Series y Películas",
    difficulty: "facil",
    difficultyLabel: "⭐ Fácil",
    time: "40 min",
    badge: "🌱 Ideal para empezar",
    tagNew: true,
    description: "El líder del grupo, siempre con un plan. No puede faltar en tu colección de Hawkins.",
    materials: ["Tijeras", "Papel (120g o más)", "Impresora", "Pegamento"]
  },
  {
    slug: "will",
    name: "Will",
    cardTitle: "🚲 Will",
    altText: "Figura de papel de Will de Stranger Things armada en papercraft",
    image: "uploads/Will.png",
    model3d: "uploads/Will.glb",
    pdfUrl: "uploads/Will.pdf",
    category: "series",
    categoryLabel: "Series y Películas",
    difficulty: "facil",
    difficultyLabel: "⭐ Fácil",
    time: "40 min",
    badge: "🌱 Ideal para empezar",
    tagNew: true,
    description: "De vuelta del Upside Down y listo para armar. El último integrante del grupo se suma a la colección.",
    materials: ["Tijeras", "Papel (120g o más)", "Impresora", "Pegamento"]
  },
  {
    slug: "mapache",
    name: "Mapache curioso",
    cardTitle: "🦝 Mapache curioso",
    altText: "Figura de papel de un mapache armado en papercraft",
    image: "uploads/Mapache.png",
    model3d: "uploads/Mapache.glb",
    pdfUrl: "uploads/Mapache.pdf",
    category: "animales",
    categoryLabel: "Animales",
    difficulty: "facil",
    difficultyLabel: "⭐ Fácil",
    time: "25 min",
    badge: "🌱 Ideal para empezar",
    tagNew: true,
    description: "Siempre metiendo la nariz donde no debe. Un modelo tierno y fácil, perfecto para sumar a tu colección de animales.",
    materials: ["Tijeras", "Papel (120g o más)", "Impresora"]
  }
];

export const CATEGORIES = [
  { key: "todos", label: "Todos", emoji: "✨" },
  { key: "animales", label: "Animales", emoji: "🐶" },
  { key: "plantas", label: "Plantas", emoji: "🌵" },
  { key: "videojuegos", label: "Videojuegos", emoji: "🎮" },
  { key: "retro", label: "Retro", emoji: "📼" },
  { key: "series", label: "Series y Películas", emoji: "🎬" }
];

export const ALL_CATEGORIES = [
  { label: "Animales", emoji: "🐶" },
  { label: "Plantas", emoji: "🌵" },
  { label: "Videojuegos", emoji: "🎮" },
  { label: "Retro", emoji: "📼" },
  { label: "Series y Películas", emoji: "🎬" },
  { label: "Infantiles", emoji: "🧸" },
  { label: "Navidad", emoji: "🎄" },
  { label: "Halloween", emoji: "🎃" },
  { label: "San Valentín", emoji: "❤️" }
];
